
name: applematch
description: Find the right tree for you
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  # Map integration

  google_maps_flutter: ^2.5.0
 

  # Local notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0

  # Location
  geolocator: ^11.0.0
  permission_handler: ^11.0.0

  # State management (optional but useful)
  provider: ^6.1.2

  # Date handling
  intl: ^0.19.0

  flutter_svg: ^2.0.9 
  haversine_distance: ^1.2.1
  latlong2: ^0.9.0 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/apple_trees.json
    - assets/icons/
    - assets/images/daddy_apple.png
    - assets/images/treeUp.png
    - assets/images/bof.png
    - assets/images/wtf.png
    - assets/images/tree.png

  fonts:
    - family: BubblegumSans
      fonts:
        - asset: assets/fonts/BubblegumSans-Regular.ttf
    - family: EuphoriaScript
      fonts:
        - asset: assets/fonts/EuphoriaScript-Regular.ttf